
DEVICE_PATH := device/huawei/CRO_U00

VENDOR_PATH := vendor/huawei/CRO_U00
-include $(VENDOR_PATH)/BoardConfigVendor.mk

# Setup MTK env {
include $(DEVICE_PATH)/mtk/BoardConfigMTK.mk
# }

TARGET_NO_BOOTLOADER := true
TARGET_NO_FACTORYIMAGE := true
TARGET_BOARD_PLATFORM := mt6580
TARGET_BOOTLOADER_BOARD_NAME := CRO-U00

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a7
TARGET_CPU_SMP := true
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7

ARCH_ARM_HAVE_VFP := true
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2625634304
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1610612736
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 251658240
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false

# Kernel {
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
ifneq ($(TARGET_BUILD_VARIANT),user)
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
endif

BOARD_KERNEL_BASE     := 0x80000000
BOARD_KERNEL_OFFSET   := 0x00008000
BOARD_KERNEL_PAGESIZE := 2048

BOARD_TAGS_OFFSET    := 0x0e000000
BOARD_RAMDISK_OFFSET := 0x04000000

BOARD_MKBOOTIMG_ARGS := \
    --tags_offset $(BOARD_TAGS_OFFSET) \
    --kernel_offset $(BOARD_KERNEL_OFFSET) \
    --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
    --board B122
# }

ifeq ($(TARGET_BUILD_VARIANT),eng)
TARGET_BUILD_TYPE := debug
endif
#COMMON_GLOBAL_CFLAGS += -DVERY_VERBOSE_LOGGING
#COMMON_GLOBAL_CPPFLAGS += -DVERY_VERBOSE_LOGGING
#COMMON_GLOBAL_CFLAGS += -DLOG_NDEBUG=0
#COMMON_GLOBAL_CPPFLAGS += -DLOG_NDEBUG=0


# Media (libstagefright_omx.so) {
#SKIP_CVE_2017_13154 := true
# }

# Audio {
#USE_CUSTOM_AUDIO_POLICY := 1
# }

#SELinux
BOARD_SEPOLICY_DIRS += \
		$(DEVICE_PATH)/sepolicy \
		device/mediatek/common/sepolicy \
		device/mediatek/mt6580/sepolicy

# CMHW
#BOARD_USES_CYANOGEN_HARDWARE := true

# Bootanimation {
TARGET_SCREEN_WIDTH := 480
TARGET_SCREEN_HEIGHT := 854
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true
# }

# Recovery
BOARD_SUPPRESS_EMMC_WIPE := true
TARGET_RECOVERY_DENSITY := hdpi
TARGET_RECOVERY_PIXEL_FORMAT := RGBA_8888
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/fstab.mt6580

# Charger {
#WITH_CM_CHARGER := false
BOARD_CHARGING_MODE_BOOTING_LPM := /sys/class/BOOT/BOOT/boot/boot_mode
BOARD_CHARGER_ENABLE_SUSPEND := true
BOARD_CHARGER_SHOW_PERCENTAGE := true
BOARD_CHARGER_DISABLE_INIT_BLANK := true
BACKLIGHT_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
# }

# EGL { settings (only VM?)
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := $(DEVICE_PATH)/configs/lib/egl/egl.cfg
BOARD_EGL_NEEDS_HANDLE_VALUE := true
BOARD_EGL_WORKAROUND_BUG_10194508 := true

MAX_VIRTUAL_DISPLAY_DIMENSION := 854
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
# }

# MTK (LineageOS support)
MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true

COMMON_GLOBAL_CFLAGS += -DDISABLE_ASHMEM_TRACKING
COMMON_GLOBAL_CPPFLAGS += -DDISABLE_ASHMEM_TRACKING

# ODEX {
ifeq ($(TARGET_BUILD_VARIANT),user)
    WITH_DEXPREOPT := true
    DONT_DEXPREOPT_PREBUILTS := false
else
    WITH_DEXPREOPT := false
    DONT_DEXPREOPT_PREBUILTS := true
    #BLOCK_BASED_OTA := false
endif
# }

# Wi-Fi {
BOARD_WLAN_DEVICE := MediaTek
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM := "/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_AP := AP
WIFI_DRIVER_FW_PATH_STA := STA
WIFI_DRIVER_FW_PATH_P2P := P2P
WIFI_DRIVER_STATE_ON := 1
WIFI_DRIVER_STATE_OFF := 0
# }

# Bluetooth {
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_HCILP_INCLUDED := 0
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_PATH)/bluetooth
# }

# RIL {
BOARD_RIL_CLASS := ../../../$(DEVICE_PATH)/ril
# }

# GPS {
TARGET_SPECIFIC_HEADER_PATH += $(DEVICE_PATH)/include/hardware/libhardware/include
# }

# Fonts {
#SMALLER_FONT_FOOTPRINT := true
#MINIMAL_FONT_FOOTPRINT := true
# }

# Properties {
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop
# }

